server:
  port: 8080
spring:
  application:
    name: @name@
  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health